# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Return parameters estimation in TVJHCM
#'
NULL

#' @export
NULL

center_dep <- function(x, n_region) {
    .Call('_BJHCM_center_dep', PACKAGE = 'BJHCM', x, n_region)
}

LL_dep <- function(b1, b2, b3, b4, b01, b02, phi, mu, theta, x1, x2, y1, y2, s1, s2, id, N) {
    .Call('_BJHCM_LL_dep', PACKAGE = 'BJHCM', b1, b2, b3, b4, b01, b02, phi, mu, theta, x1, x2, y1, y2, s1, s2, id, N)
}

LL_id_dep <- function(b1, b2, b3, b4, b01, b02, phi, sigma, mu, theta, x1, x2, y1, y2, s1, s2, N) {
    .Call('_BJHCM_LL_id_dep', PACKAGE = 'BJHCM', b1, b2, b3, b4, b01, b02, phi, sigma, mu, theta, x1, x2, y1, y2, s1, s2, N)
}

target_phi_dep <- function(b1, b2, b3, b4, b01, b02, phi, sigma, mu, theta, x1, x2, y1, y2, s1, s2, id, no_patient, N, x1_new, k) {
    .Call('_BJHCM_target_phi_dep', PACKAGE = 'BJHCM', b1, b2, b3, b4, b01, b02, phi, sigma, mu, theta, x1, x2, y1, y2, s1, s2, id, no_patient, N, x1_new, k)
}

target_sigma_dep <- function(phi, no_patient) {
    .Call('_BJHCM_target_sigma_dep', PACKAGE = 'BJHCM', phi, no_patient)
}

target_sigma_epsilon_dep <- function(theta, N, ni, rho) {
    .Call('_BJHCM_target_sigma_epsilon_dep', PACKAGE = 'BJHCM', theta, N, ni, rho)
}

theta_pow_sum_dep <- function(theta, N, ni) {
    .Call('_BJHCM_theta_pow_sum_dep', PACKAGE = 'BJHCM', theta, N, ni)
}

theta_lag_sum_dep <- function(theta, N, ni) {
    .Call('_BJHCM_theta_lag_sum_dep', PACKAGE = 'BJHCM', theta, N, ni)
}

rand_gen_dep <- function() {
    .Call('_BJHCM_rand_gen_dep', PACKAGE = 'BJHCM')
}

normalRandom_dep <- function() {
    .Call('_BJHCM_normalRandom_dep', PACKAGE = 'BJHCM')
}

metroplis_phi_dep <- function(b1, b2, b3, b4, b01, b02, phi_curr, sigma, mu, theta, x1, x2, y1, y2, s1, s2, id, no_patient, N, x1_prev, j, scale) {
    .Call('_BJHCM_metroplis_phi_dep', PACKAGE = 'BJHCM', b1, b2, b3, b4, b01, b02, phi_curr, sigma, mu, theta, x1, x2, y1, y2, s1, s2, id, no_patient, N, x1_prev, j, scale)
}

metroplis_phi_id_dep <- function(b1, b2, b3, b4, b01, b02, sigma, mu, theta, x1, x2, y1, y2, s1, s2, N, x1_prev, scale) {
    .Call('_BJHCM_metroplis_phi_id_dep', PACKAGE = 'BJHCM', b1, b2, b3, b4, b01, b02, sigma, mu, theta, x1, x2, y1, y2, s1, s2, N, x1_prev, scale)
}

target_theta_dep <- function(b1, b2, b3, b4, b01, b02, phi, mu, theta, rho, sigma_epsilon, x1, x2, y1, y2, s1, s2, id, N, ni, x1_new, k, maxni) {
    .Call('_BJHCM_target_theta_dep', PACKAGE = 'BJHCM', b1, b2, b3, b4, b01, b02, phi, mu, theta, rho, sigma_epsilon, x1, x2, y1, y2, s1, s2, id, N, ni, x1_new, k, maxni)
}

metroplis_theta_dep <- function(b1, b2, b3, b4, b01, b02, phi, mu, theta_curr, rho, sigma_epsilon, x1, x2, y1, y2, s1, s2, id, N, ni, x1_prev, j, scale, maxni) {
    .Call('_BJHCM_metroplis_theta_dep', PACKAGE = 'BJHCM', b1, b2, b3, b4, b01, b02, phi, mu, theta_curr, rho, sigma_epsilon, x1, x2, y1, y2, s1, s2, id, N, ni, x1_prev, j, scale, maxni)
}

MH_dep <- function(b1, b2, b3, b4, b01, b02, phi, sigma, mu, theta, rho, sigma_epsilon, x1, x2, y1, y2, s1, s2, id, no_pat_p, n_sample, N_p, scale, ni, maxni) {
    .Call('_BJHCM_MH_dep', PACKAGE = 'BJHCM', b1, b2, b3, b4, b01, b02, phi, sigma, mu, theta, rho, sigma_epsilon, x1, x2, y1, y2, s1, s2, id, no_pat_p, n_sample, N_p, scale, ni, maxni)
}

#' estimation based on TVJHCM
#'
#' @param x A matrix.
#' @export
NULL

center_dep_vec <- function(x, n_region) {
    .Call('_BJHCM_center_dep_vec', PACKAGE = 'BJHCM', x, n_region)
}

LL_dep_vec <- function(b1, b2, b01, b02, phi, mu, theta, x, y1, y2, s1, s2, id, N, p, ni, maxni) {
    .Call('_BJHCM_LL_dep_vec', PACKAGE = 'BJHCM', b1, b2, b01, b02, phi, mu, theta, x, y1, y2, s1, s2, id, N, p, ni, maxni)
}

LLi_dep_vec <- function(b1, b2, b01, b02, phi, mu, theta, x, y1, y2, s1, s2, id, N, p, j_start, j_end, ni, maxni) {
    .Call('_BJHCM_LLi_dep_vec', PACKAGE = 'BJHCM', b1, b2, b01, b02, phi, mu, theta, x, y1, y2, s1, s2, id, N, p, j_start, j_end, ni, maxni)
}

LL_id_dep_vec <- function(b1, b2, b01, b02, phi, mu, theta, x, y1, y2, s1, s2, N, p) {
    .Call('_BJHCM_LL_id_dep_vec', PACKAGE = 'BJHCM', b1, b2, b01, b02, phi, mu, theta, x, y1, y2, s1, s2, N, p)
}

target_phi_dep_vec <- function(b1, b2, b01, b02, phi, sigma, mu, theta, x, y1, y2, s1, s2, id, no_patient, N, x1_new, k, p, j_start, j_end, ni, maxni) {
    .Call('_BJHCM_target_phi_dep_vec', PACKAGE = 'BJHCM', b1, b2, b01, b02, phi, sigma, mu, theta, x, y1, y2, s1, s2, id, no_patient, N, x1_new, k, p, j_start, j_end, ni, maxni)
}

target_sigma_dep_vec <- function(phi, no_patient) {
    .Call('_BJHCM_target_sigma_dep_vec', PACKAGE = 'BJHCM', phi, no_patient)
}

target_sigma_epsilon_dep_vec <- function(theta, N, ni, rho) {
    .Call('_BJHCM_target_sigma_epsilon_dep_vec', PACKAGE = 'BJHCM', theta, N, ni, rho)
}

theta_pow_sum_dep_vec <- function(theta, N, ni) {
    .Call('_BJHCM_theta_pow_sum_dep_vec', PACKAGE = 'BJHCM', theta, N, ni)
}

theta_lag_sum_dep_vec <- function(theta, N, ni) {
    .Call('_BJHCM_theta_lag_sum_dep_vec', PACKAGE = 'BJHCM', theta, N, ni)
}

rand_gen_vec <- function() {
    .Call('_BJHCM_rand_gen_vec', PACKAGE = 'BJHCM')
}

normalRandom_vec <- function() {
    .Call('_BJHCM_normalRandom_vec', PACKAGE = 'BJHCM')
}

metroplis_phi_dep_vec <- function(b1, b2, b01, b02, phi_curr, sigma, mu, theta, x, y1, y2, s1, s2, id, no_patient, N, x1_prev, j, scale, p, j_start, j_end, ni, maxni) {
    .Call('_BJHCM_metroplis_phi_dep_vec', PACKAGE = 'BJHCM', b1, b2, b01, b02, phi_curr, sigma, mu, theta, x, y1, y2, s1, s2, id, no_patient, N, x1_prev, j, scale, p, j_start, j_end, ni, maxni)
}

metroplis_phi_id_dep_vec <- function(b1, b2, b01, b02, sigma, mu, theta, x, y1, y2, s1, s2, N, x1_prev, scale, p) {
    .Call('_BJHCM_metroplis_phi_id_dep_vec', PACKAGE = 'BJHCM', b1, b2, b01, b02, sigma, mu, theta, x, y1, y2, s1, s2, N, x1_prev, scale, p)
}

target_theta_dep_vec <- function(b1, b2, b01, b02, phi, mu, theta, rho, sigma_epsilon, x, y1, y2, s1, s2, id, N, ni, x1_new, k, maxni, p, j_start, j_end) {
    .Call('_BJHCM_target_theta_dep_vec', PACKAGE = 'BJHCM', b1, b2, b01, b02, phi, mu, theta, rho, sigma_epsilon, x, y1, y2, s1, s2, id, N, ni, x1_new, k, maxni, p, j_start, j_end)
}

metroplis_theta_dep_vec <- function(b1, b2, b01, b02, phi, mu, theta_curr, rho, sigma_epsilon, x, y1, y2, s1, s2, id, N, ni, x1_prev, j, scale, maxni, p, j_start, j_end) {
    .Call('_BJHCM_metroplis_theta_dep_vec', PACKAGE = 'BJHCM', b1, b2, b01, b02, phi, mu, theta_curr, rho, sigma_epsilon, x, y1, y2, s1, s2, id, N, ni, x1_prev, j, scale, maxni, p, j_start, j_end)
}

MH_dep_vec <- function(b1, b2, b01, b02, phi, sigma, mu, theta, rho, sigma_epsilon, x, y1, y2, s1, s2, id, no_pat_p, n_sample, N_p, scale, ni, maxni, p, j_start, j_end) {
    .Call('_BJHCM_MH_dep_vec', PACKAGE = 'BJHCM', b1, b2, b01, b02, phi, sigma, mu, theta, rho, sigma_epsilon, x, y1, y2, s1, s2, id, no_pat_p, n_sample, N_p, scale, ni, maxni, p, j_start, j_end)
}

#' Return paramter estimation in TJCM
#'
NULL

#' @export
NULL

center <- function(x, n_region) {
    .Call('_BJHCM_center', PACKAGE = 'BJHCM', x, n_region)
}

LL <- function(b1, b2, b3, b4, b01, b02, phi, theta, x1, x2, y1, y2, s1, s2, id, N) {
    .Call('_BJHCM_LL', PACKAGE = 'BJHCM', b1, b2, b3, b4, b01, b02, phi, theta, x1, x2, y1, y2, s1, s2, id, N)
}

LL_id <- function(b1, b2, b3, b4, b01, b02, phi, theta, x1, x2, y1, y2, s1, s2, N) {
    .Call('_BJHCM_LL_id', PACKAGE = 'BJHCM', b1, b2, b3, b4, b01, b02, phi, theta, x1, x2, y1, y2, s1, s2, N)
}

target_phi <- function(b1, b2, b3, b4, b01, b02, phi, sigma, theta, x1, x2, y1, y2, s1, s2, id, no_patient, N, x1_new, k) {
    .Call('_BJHCM_target_phi', PACKAGE = 'BJHCM', b1, b2, b3, b4, b01, b02, phi, sigma, theta, x1, x2, y1, y2, s1, s2, id, no_patient, N, x1_new, k)
}

target_sigma <- function(phi, no_patient) {
    .Call('_BJHCM_target_sigma', PACKAGE = 'BJHCM', phi, no_patient)
}

rand_gen <- function() {
    .Call('_BJHCM_rand_gen', PACKAGE = 'BJHCM')
}

normalRandom <- function() {
    .Call('_BJHCM_normalRandom', PACKAGE = 'BJHCM')
}

metroplis_phi <- function(b1, b2, b3, b4, b01, b02, phi_curr, sigma, theta, x1, x2, y1, y2, s1, s2, id, no_patient, N, x1_prev, j, scale) {
    .Call('_BJHCM_metroplis_phi', PACKAGE = 'BJHCM', b1, b2, b3, b4, b01, b02, phi_curr, sigma, theta, x1, x2, y1, y2, s1, s2, id, no_patient, N, x1_prev, j, scale)
}

metroplis_phi_id <- function(b1, b2, b3, b4, b01, b02, theta, sigma, x1, x2, y1, y2, s1, s2, N, x1_prev, scale) {
    .Call('_BJHCM_metroplis_phi_id', PACKAGE = 'BJHCM', b1, b2, b3, b4, b01, b02, theta, sigma, x1, x2, y1, y2, s1, s2, N, x1_prev, scale)
}

MH_joint_model <- function(b1, b2, b3, b4, b01, b02, phi, sigma, theta, x1, x2, y1, y2, s1, s2, id, no_pat_p, n_sample, N_p, scale) {
    .Call('_BJHCM_MH_joint_model', PACKAGE = 'BJHCM', b1, b2, b3, b4, b01, b02, phi, sigma, theta, x1, x2, y1, y2, s1, s2, id, no_pat_p, n_sample, N_p, scale)
}

center_vec <- function(x, n_region) {
    .Call('_BJHCM_center_vec', PACKAGE = 'BJHCM', x, n_region)
}

LL_vec <- function(b1, b2, b01, b02, phi, theta, x, y1, y2, s1, s2, id, N, p, ni, maxni) {
    .Call('_BJHCM_LL_vec', PACKAGE = 'BJHCM', b1, b2, b01, b02, phi, theta, x, y1, y2, s1, s2, id, N, p, ni, maxni)
}

LLi_vec <- function(b1, b2, b01, b02, phi, theta, x, y1, y2, s1, s2, id, N, p, j_start, j_end, ni, maxni) {
    .Call('_BJHCM_LLi_vec', PACKAGE = 'BJHCM', b1, b2, b01, b02, phi, theta, x, y1, y2, s1, s2, id, N, p, j_start, j_end, ni, maxni)
}

LL_id_vec <- function(b1, b2, b01, b02, phi, theta, x, y1, y2, s1, s2, N, p) {
    .Call('_BJHCM_LL_id_vec', PACKAGE = 'BJHCM', b1, b2, b01, b02, phi, theta, x, y1, y2, s1, s2, N, p)
}

target_phi_vec <- function(b1, b2, b01, b02, phi, sigma, theta, x, y1, y2, s1, s2, id, no_patient, N, x1_new, k, p, j_start, j_end, ni, maxni) {
    .Call('_BJHCM_target_phi_vec', PACKAGE = 'BJHCM', b1, b2, b01, b02, phi, sigma, theta, x, y1, y2, s1, s2, id, no_patient, N, x1_new, k, p, j_start, j_end, ni, maxni)
}

target_sigma_vec <- function(phi, no_patient) {
    .Call('_BJHCM_target_sigma_vec', PACKAGE = 'BJHCM', phi, no_patient)
}

metroplis_phi_vec <- function(b1, b2, b01, b02, phi_curr, sigma, theta, x, y1, y2, s1, s2, id, no_patient, N, x1_prev, j, scale, p, j_start, j_end, ni, maxni) {
    .Call('_BJHCM_metroplis_phi_vec', PACKAGE = 'BJHCM', b1, b2, b01, b02, phi_curr, sigma, theta, x, y1, y2, s1, s2, id, no_patient, N, x1_prev, j, scale, p, j_start, j_end, ni, maxni)
}

metroplis_phi_id_vec <- function(b1, b2, b01, b02, sigma, theta, x, y1, y2, s1, s2, N, x1_prev, scale, p) {
    .Call('_BJHCM_metroplis_phi_id_vec', PACKAGE = 'BJHCM', b1, b2, b01, b02, sigma, theta, x, y1, y2, s1, s2, N, x1_prev, scale, p)
}

MH_joint_model_vec <- function(b1, b2, b01, b02, phi, sigma, theta, x, y1, y2, s1, s2, id, no_pat_p, n_sample, N_p, scale, p, j_start, j_end, ni, maxni) {
    .Call('_BJHCM_MH_joint_model_vec', PACKAGE = 'BJHCM', b1, b2, b01, b02, phi, sigma, theta, x, y1, y2, s1, s2, id, no_pat_p, n_sample, N_p, scale, p, j_start, j_end, ni, maxni)
}

